import{a as w,S as E,i as d}from"./assets/vendor-g5NYb1XI.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const g of s.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&a(g)}).observe(document,{childList:!0,subtree:!0});function o(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(r){if(r.ep)return;r.ep=!0;const s=o(r);fetch(r.href,s)}})();const v="48661661-399e17c2888aa32e2cfb6a652",h=async(e,t=1)=>{var o;try{const a=await w.get("https://pixabay.com/api/",{params:{key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:40}});return{images:a.data.hits,totalHits:a.data.totalHits}}catch(a){throw console.error("Error fetching images: ",((o=a.response)==null?void 0:o.data)||a.message),new Error("Unable to fetch images.")}},I=document.getElementById("gallery"),B=new E(".gallery-link",{captionsData:"alt",captionDelay:250}),P=()=>{const e=document.querySelectorAll(".gallery-card");if(e.length>0){const t=e[0].getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}},f=e=>{if(e.length===0){b();return}I.innerHTML+=e.map(t=>`
    <div class="gallery-card">
      <a href="${t.largeImageURL}" class="gallery-link">
        <img src="${t.webformatURL}" alt="${t.tags}" class="gallery-image">
      </a>
      <div class="image-info">
        <p><strong>Likes:</strong> ${t.likes}</p>
        <p><strong>Views:</strong> ${t.views}</p>
        <p><strong>Comments:</strong> ${t.comments}</p>
        <p><strong>Downloads:</strong> ${t.downloads}</p>
      </div>
    </div>
  `).join(""),B.refresh(),P()},b=()=>{d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",onOpening:function(){const e=document.querySelector(".iziToast");e&&(e.style.borderBottom="2px solid #ffbebe",e.style.borderRadius="4px",e.style.padding="20px",e.style.width="432px",e.style.height="88px")}})},y=e=>{d.error({title:"Error",message:e,position:"topRight"})},L=document.getElementById("search-form"),u=document.getElementById("search-input"),x=document.querySelector("button"),p=document.getElementById("gallery"),l=document.querySelector(".loader"),n=document.getElementById("load-more-btn");let i=1,m="",c=0;L.classList.add("search-form");u.classList.add("search-input");x.classList.add("search-button");p.classList.add("gallery");L.addEventListener("submit",async e=>{e.preventDefault();const t=u.value.trim();if(!t){y("Please enter a search term.");return}m=t,i=1,c=0,p.innerHTML="",n.style.display="none",l.style.display="block";try{const{images:o,totalHits:a}=await h(m,i);if(c=a,o.length===0){b();return}f(o),o.length>0&&(p.insertAdjacentElement("afterend",n),n.style.display="block"),c<=40&&(n.style.display="none",d.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{y("Failed to fetch images. Please try again later.")}finally{l.style.display="none"}u.value=""});n.addEventListener("click",async()=>{i+=1,n.insertAdjacentElement("afterend",l),l.style.display="block";try{const{images:e,totalHits:t}=await h(m,i);if(c=t,e.length===0){n.style.display="none";return}f(e),(i-1)*40+e.length>=c&&(n.style.display="none",d.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{y("Failed to fetch more images. Please try again later.")}finally{l.style.display="none"}});
//# sourceMappingURL=index.js.map
