import{a as L,S as v,i as d}from"./assets/vendor-g5NYb1XI.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const g of o.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&a(g)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const E="48661661-399e17c2888aa32e2cfb6a652",m=async(t,e=1)=>{var s;try{const a=await L.get("https://pixabay.com/api/",{params:{key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:40}});return{images:a.data.hits,totalHits:a.data.totalHits}}catch(a){throw console.error("Error fetching images: ",((s=a.response)==null?void 0:s.data)||a.message),new Error("Unable to fetch images.")}},I=document.getElementById("gallery"),B=new v(".gallery-link",{captionsData:"alt",captionDelay:250}),P=()=>{const t=document.querySelectorAll(".gallery-card");if(t.length>0){const e=t[0].getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}},f=t=>{if(t.length===0){b();return}I.innerHTML+=t.map(e=>`
    <div class="gallery-card">
      <a href="${e.largeImageURL}" class="gallery-link">
        <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-image">
      </a>
      <div class="image-info">
        <p><strong>Likes:</strong> ${e.likes}</p>
        <p><strong>Views:</strong> ${e.views}</p>
        <p><strong>Comments:</strong> ${e.comments}</p>
        <p><strong>Downloads:</strong> ${e.downloads}</p>
      </div>
    </div>
  `).join(""),B.refresh(),P()},b=()=>{d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",onOpening:function(){const t=document.querySelector(".iziToast");t&&(t.style.borderBottom="2px solid #ffbebe",t.style.borderRadius="4px",t.style.padding="20px",t.style.width="432px",t.style.height="88px")}})},y=t=>{d.error({title:"Error",message:t,position:"topRight"})},w=document.getElementById("search-form"),u=document.getElementById("search-input"),R=document.querySelector("button"),p=document.getElementById("gallery"),i=document.querySelector(".loader"),n=document.getElementById("load-more-btn");let c=1,h="",l=0;w.classList.add("search-form");u.classList.add("search-input");R.classList.add("search-button");p.classList.add("gallery");w.addEventListener("submit",async t=>{t.preventDefault();const e=u.value.trim();if(!e){y("Please enter a search term.");return}h=e,c=1,l=0,p.innerHTML="",n.style.display="none",i.style.display="block";try{const{images:s,totalHits:a}=await m(h,c);if(l=a,s.length===0){b();return}f(s),s.length>0&&(p.insertAdjacentElement("afterend",n),n.style.display="block"),l<=40&&(n.style.display="none",d.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{y("Failed to fetch images. Please try again later.")}finally{i.style.display="none"}u.value=""});n.addEventListener("click",async()=>{const t=c*40;if(t>=l){n.style.display="none",d.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}c+=1,n.insertAdjacentElement("afterend",i),i.style.display="block";try{const{images:e,totalHits:s}=await m(h,c);l=s,e.length===0||e.length<40&&t>=l?(n.style.display="none",d.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):f(e)}catch{y("Failed to fetch more images. Please try again later.")}finally{i.style.display="none"}});
//# sourceMappingURL=index.js.map
